// Register User
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
		"name": "Faij Alam",
		"email": "faijalam@gmail.com",
		"password": "Faij@123"
}

###
// Login User
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
		"email": "nimmi@gmail.com",
		"password": "Nimmi@123"
}

###
// Get User Profile
GET http://localhost:3000/api/user/find/66cf2e30a2c3a8269e37ee26

###
// Get All Users
GET http://localhost:3000/api/user/find

###
// Create Chat
POST http://localhost:3000/api/chats
Content-Type: application/json

{
		"firstId": "66d096d145fa1c375970",
		"secondId": "66d0c8062b529b30e7d0"
}

###
// Find All Chat
GET http://localhost:3000/api/chats/66d19bd9ff74252f1ad6489e

###
// Find Single Chat
GET http://localhost:3000/api/chats/find/66d096d145ff2e4a1c375970/66d0c8063ebb2b529b30e7d0

###
// Send Message
POST http://localhost:3000/api/messages
Content-Type: application/json

{
		"chatId": "66d1d692ff74252f1ad64b7f",
		"senderId": "66d096d145ff2e4a1c375970",
		"text": "Chat 1 A to R."
}

###
// Get All Messages
GET http://localhost:3000/api/messages/66d1d4d7ff74252f1ad64b5a